"""
csv_to_js.py

Converts MrWorldwide.csv → src/data/books.js

Usage:
    python csv_to_js.py                          # uses default paths below
    python csv_to_js.py data.csv                 # custom CSV path
    python csv_to_js.py data.csv out/books.js    # custom CSV + output path
"""

import csv
import json
import sys
from pathlib import Path
from utils.regions import *

CSV_PATH = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("../data/MrWorldwide.csv")
OUT_PATH = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("../site/src/data/books.js")

def parse_rating(raw: str) -> float | None:
    cleaned = raw.strip().replace(",", ".")
    try:
        return float(cleaned) if cleaned else None
    except ValueError:
        return None

def parse_row(row: list[str]) -> dict | None:
    """Parse one CSV row. Returns None if the row should be skipped."""
    if not row:
        return None
    country = row[0].strip()

    if not country or country.startswith("*") or country.startswith("#"):
        return None

    title        = row[1].strip()  if len(row) > 1 else ""
    author       = row[2].strip()  if len(row) > 2 else ""
    genre        = row[3].strip()  if len(row) > 3 else ""
    date         = row[4].strip()  if len(row) > 4 else ""
    language     = row[5].strip()  if len(row) > 5 else ""
    rating_raw   = row[6].strip()  if len(row) > 6 else ""
    female_flag  = row[7].strip()  if len(row) > 7 else ""

    coords = COORDS.get(country)

    return {
        "country":      country,
        "title":        title,
        "author":       author,
        "genres":       [g.strip() for g in genre.split(",") if g.strip()],
        "date":         date,
        "language":     language,
        "rating":       parse_rating(rating_raw),
        "femaleAuthor": bool(female_flag),
        "read":         bool(date),
        "region":       REGIONS.get(country, "Other"),
        "lat":          coords[0] if coords else None,
        "lng":          coords[1] if coords else None,
    }

def convert(csv_path: Path, out_path: Path) -> None:
    if not csv_path.exists():
        print(f"CSV not found: {csv_path}")
        raise SystemExit(1)

    books = []
    with csv_path.open(encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)  # skip header
        for row in reader:
            entry = parse_row(row)
            if entry:
                books.append(entry)

    read_count  = sum(1 for b in books if b["read"])
    rated_count = sum(1 for b in books if b["rating"] is not None)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by csv_to_js.py — do not edit by hand\n")
        f.write("// Last updated: " + __import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M") + "\n\n")
        f.write("export const BOOKS = ")
        f.write(json.dumps(books, indent=2, ensure_ascii=False))
        f.write(";\n\n")
        f.write(f"export const TOTAL_COUNTRIES = 195;\n")

    print(f"Written {len(books)} countries → {out_path}")
    print(f"    {read_count} read · {rated_count} rated · {len(books) - read_count} to go")


if __name__ == "__main__":
    convert(CSV_PATH, OUT_PATH)